// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PassMeta is an autogenerated mock type for the PassMeta type
type PassMeta struct {
	mock.Mock
}

// UpdateMeta provides a mock function with given fields: oldValues
func (_m *PassMeta) UpdateMeta(oldValues map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(oldValues)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(oldValues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(oldValues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
