// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetSurveyTemplate provides a mock function with given fields: ctx, id
func (_m *Usecase) GetSurveyTemplate(ctx context.Context, id int) (string, error) {
	ret := _m.Called(ctx, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSurveyTemplate provides a mock function with given fields: ctx, _a1, id
func (_m *Usecase) SetSurveyTemplate(ctx context.Context, _a1 string, id int) error {
	ret := _m.Called(ctx, _a1, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, _a1, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitSurvey provides a mock function with given fields: ctx, _a1, customerID
func (_m *Usecase) SubmitSurvey(ctx context.Context, _a1 string, customerID string) error {
	ret := _m.Called(ctx, _a1, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, _a1, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
