version: "3"

services:
  main_serivce:
    image: main_service
    ports:
      - "8080:8080"
      - "8082:8082"
    env_file:
      - .env

  staff:
    image: staff_service
    env_file:
      - .env
    ports:
      - "8084:8084"
      - "8083:8083"

  survey:
    image: survey_service
    env_file:
      - .env
    ports:
      - "8085:8085"
      - "8086:8086"