version: "3"

services:
  main_serivce:
    image: main_service
    ports:
      - "8080:8080"
      - "8082:8082"
    env_file:
      - envs/.env
    depends_on:
      - redis
      - postgres

  staff:
    image: staff_service
    env_file:
      - envs/.env
    ports:
      - "8084:8084"
      - "8083:8083"
    depends_on:
      - redis
      - postgres

  survey:
    image: survey_service
    env_file:
      - envs/.env
    ports:
      - "8085:8085"
      - "8086:8086"
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis

  postgres:
    image: postgres
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
