version: "3"

services:
  builder:
    build:
      context: .
      dockerfile: docker/builder.Dockerfile
    env_file:
      - docker/.env
  main_serivce:
    build:
      context: .
      dockerfile: docker/main_service.Dockerfile
    container_name: main_service_container
    ports:
    - 8080:8080
    env_file:
      - docker/.env

