version: "3"

services:
  main_serivce:
    build:
      context: docker
      dockerfile: docker/main_service.Dockerfile
    container_name: main_service_container
    ports:
    - 8080:8080
    env_file:
      - docker/.env

