version: "3"

services:
  builder:
    image: dependencies:dependencies
    build:
      context: .
      dockerfile: docker/builder.Dockerfile
    env_file:
      - .env

  main_serivce:
    build:
      context: .
      dockerfile: docker/main_service.Dockerfile
    container_name: main_service_container
    ports:
    - 8080:8080
    env_file:
      - .env
    depends_on:
      - builder
