// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	google_geocoder "2020_1_drop_table/internal/pkg/google_geocoder"

	mock "github.com/stretchr/testify/mock"
)

// GoogleGeoCoder is an autogenerated mock type for the GoogleGeoCoder type
type GoogleGeoCoder struct {
	mock.Mock
}

// GetGeoByAddress provides a mock function with given fields: address
func (_m *GoogleGeoCoder) GetGeoByAddress(address string) (google_geocoder.GoogleGeoResponseResults, error) {
	ret := _m.Called(address)

	var r0 google_geocoder.GoogleGeoResponseResults
	if rf, ok := ret.Get(0).(func(string) google_geocoder.GoogleGeoResponseResults); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(google_geocoder.GoogleGeoResponseResults)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
