// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	customer "2020_1_drop_table/internal/app/customer/delivery/grpc/protobuff"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CustomerGRPCHandlerServer is an autogenerated mock type for the CustomerGRPCHandlerServer type
type CustomerGRPCHandlerServer struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *CustomerGRPCHandlerServer) Add(_a0 context.Context, _a1 *customer.Customer) (*customer.Customer, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *customer.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *customer.Customer) *customer.Customer); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *customer.Customer) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
