name: Docker Build

on:
  push:
    branches:
      - master
      - dev
      - testci
  pull_request:
    branches:
      - master
      - dev
      - testci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Testing
        run: make test-coverage
      - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: ls
          run: ls -la
      - name: Build Docker image
          run: make build-for-deploy
      - name: Push the image
          run: docker push droptable14/main_service


