name: Docker Build

on:
  push:
    branches:
      - master
      - dev
      - testci
  pull_request:
    branches:
      - master
      - dev
      - testci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - name: Testing
#        run: make test-coverage
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: ls
        run: ls -la
      - name: Build Docker image
        run: docker build -t droptable14/dependencies -f ./docker/builder.Dockerfile . &&
          docker build -t droptable14/main_service -f ./docker/main_service.Dockerfile . &&
          docker build -t droptable14/staff_service -f ./docker/staff.Dockerfile . &&
          docker build -t droptable14/survey_service -f ./docker/survey.Dockerfile .
      - name: Push the image
        run: docker push droptable14/dependencies:${GITHUB_SHA::8} &&
         docker push droptable14/main_service:${GITHUB_SHA::8} &&
         docker push droptable14/staff_service:${GITHUB_SHA::8} &&
         docker push droptable14/survey_service:${GITHUB_SHA::8}


